package BaiThucMauDinhDang;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class BieuThucMau extends javax.swing.JFrame {

    /**
     * Creates new form BieuThucMau
     */
    public BieuThucMau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_hoTen = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        lbl_hoTen1 = new javax.swing.JLabel();
        txt_nguoiYeu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_hoTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_hoTen.setText("Ho Ten");

        txt_hoTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Hong"},
                {"Hoa"},
                {"Heu"},
                {"Hua"},
                {null}
            },
            new String [] {
                "Ten"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        btn_them.setText("Them");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        lbl_hoTen1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_hoTen1.setText("Ho ten ny:");

        txt_nguoiYeu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_hoTen)
                                    .addComponent(lbl_hoTen1))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nguoiYeu, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(btn_them)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hoTen)
                    .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hoTen1)
                    .addComponent(txt_nguoiYeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_them)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        tbl.setRowSelectionInterval(2, 2);
    }//GEN-LAST:event_formWindowOpened

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        check();
    }//GEN-LAST:event_btn_themActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BieuThucMau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BieuThucMau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BieuThucMau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BieuThucMau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BieuThucMau().setVisible(true);
            }
        });
    }

    public void check() {
        String tam, tam1;
        tam = txt_hoTen.getText();
        tam1 = txt_nguoiYeu.getText();

        // kt null
        if (tam.isEmpty()) { // kiem tra trong
            JOptionPane.showMessageDialog(this, "Ho Ten null");
            txt_hoTen.requestFocus(); // dat chuot vao ho tens
            txt_hoTen.setBackground(Color.YELLOW);
            return;
        } else { // ho ten khong null 
            // kiem tra email co hop le hay khong
            String p_hoten = "[a-zA-Z ]+";
            if (tam.matches(p_hoten) == false) { // du lieu khong hop le
                JOptionPane.showMessageDialog(this, "Ho Ten Khong dung kieu");
                txt_hoTen.requestFocus(); // dat chuot vao ho tens
                txt_hoTen.setBackground(Color.YELLOW);
                return;
            } else {
                txt_hoTen.setBackground(Color.WHITE);
            }
        }
        
        if (tam1.isEmpty()) { // kiem tra trong
            JOptionPane.showMessageDialog(this, "Ho ten ny null");
            txt_nguoiYeu.requestFocus(); // dat chuot vao ho tens
            txt_nguoiYeu.setBackground(Color.YELLOW);
            return;
        } else { // ho ten khong null 
            // kiem tra email co hop le hay khong
            String p_hoten = "[a-zA-Z ]+";
            if (tam1.matches(p_hoten) == false) { // du lieu khong hop le
                JOptionPane.showMessageDialog(this, "Ho Ten ny Khong dung kieu");
                txt_nguoiYeu.requestFocus(); // dat chuot vao ho tens
                txt_nguoiYeu.setBackground(Color.YELLOW);
                return;
            } else {
                txt_nguoiYeu.setBackground(Color.WHITE);
            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_them;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_hoTen;
    private javax.swing.JLabel lbl_hoTen1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_nguoiYeu;
    // End of variables declaration//GEN-END:variables
}
