package Labs3;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class quanLySinhVien extends javax.swing.JFrame {

    /**
     * Creates new form quanLySinhVien
     */
    public quanLySinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chk_phanThuong = new javax.swing.JCheckBox();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_nhapMoi = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();
        txt_hoVaTen = new javax.swing.JTextField();
        txt_hocLuc = new javax.swing.JTextField();
        txt_diem = new javax.swing.JTextField();
        cbo_nganh = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btn_sapXepTen = new javax.swing.JButton();
        btn_sapXepDiem = new javax.swing.JButton();
        btn_write = new javax.swing.JButton();
        btn_read = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("QUAN LY SINH VIEN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("HO VA TEN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("DIEM");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("NGANH");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("HOC LUC");

        chk_phanThuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chk_phanThuong.setText("Co phan thuong?");
        chk_phanThuong.setEnabled(false);

        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_them.setText("THEM");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_xoa.setText("XOA");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_nhapMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_nhapMoi.setText("NHAP MOI");
        btn_nhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhapMoiActionPerformed(evt);
            }
        });

        btn_capNhat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_capNhat.setText("CAP NHAT");
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });

        txt_hoVaTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_hocLuc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_hocLuc.setEnabled(false);
        txt_hocLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hocLucActionPerformed(evt);
            }
        });

        txt_diem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_diem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diemActionPerformed(evt);
            }
        });
        txt_diem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_diemKeyReleased(evt);
            }
        });

        cbo_nganh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbo_nganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HO VA TEN", "DIEM", "NGANH", "HOC LUC", "THUONG"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        btn_sapXepTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sapXepTen.setText("Sap xep theo ten");
        btn_sapXepTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sapXepTenActionPerformed(evt);
            }
        });

        btn_sapXepDiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sapXepDiem.setText("Sap xep theo diem");
        btn_sapXepDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sapXepDiemActionPerformed(evt);
            }
        });

        btn_write.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_write.setText("WRITE FILE");
        btn_write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_writeActionPerformed(evt);
            }
        });

        btn_read.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_read.setText("READ FILE");
        btn_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_sapXepTen)
                        .addGap(60, 60, 60)
                        .addComponent(btn_sapXepDiem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel1))
                                    .addComponent(txt_hoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chk_phanThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_diem, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_hocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_them)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_capNhat)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_xoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_nhapMoi))
                                    .addComponent(cbo_nganh, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_write, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_read, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_hoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_write))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_diem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_read)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbo_nganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_hocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chk_phanThuong)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nhapMoi)
                    .addComponent(btn_them)
                    .addComponent(btn_capNhat)
                    .addComponent(btn_xoa))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sapXepTen)
                    .addComponent(btn_sapXepDiem))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhapMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btn_nhapMoiActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        
        this.removeStudent();
        JOptionPane.showMessageDialog(this, "Ban da xoa mot student");
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void txt_hocLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hocLucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hocLucActionPerformed

    private void txt_diemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diemActionPerformed

    ArrayList<Student> mangHocSinh = new ArrayList<>();
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        this.setTitle("Labs3");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        cbo_nganh.removeAllItems();
        cbo_nganh.addItem("Thiet ke trang Web");
        cbo_nganh.addItem("Ung dung phan mem");
        cbo_nganh.addItem("Lap trinh may tinh");
        cbo_nganh.addItem("Thiet ke do hoa");
        txt_hocLuc.disable();
        
        Student s = new Student("Nguyen Chi Thuan", 9.9, "CNTT");
        mangHocSinh.add(s);
        fillTable();
    }//GEN-LAST:event_formWindowOpened

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        this.addStudent();
        JOptionPane.showMessageDialog(this, "Ban da nhap them mot student");
    }//GEN-LAST:event_btn_themActionPerformed

    private void txt_diemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_diemKeyReleased
        // TODO add your handling code here:
        Student sv = readStudent();
        if(sv.getMarks() > 10) {
            sv.setMarks(10);
            txt_diem.setText("10");
        }
        if(sv.getMarks() < 0) {
            sv.setMarks(0);
            txt_diem.setText("0");
        }
        txt_hocLuc.setText(sv.getGrade());
        chk_phanThuong.setSelected(sv.isBonus());
    }//GEN-LAST:event_txt_diemKeyReleased

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        this.writeStudent(mangHocSinh.get(tbl.getSelectedRow()));
    }//GEN-LAST:event_tblMouseClicked

    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        // TODO add your handling code here:
        this.updateStudent();
        JOptionPane.showMessageDialog(this, "Ban da cap nhat mot student");
    }//GEN-LAST:event_btn_capNhatActionPerformed

    private void btn_sapXepDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sapXepDiemActionPerformed
        // TODO add your handling code here:
        orderByMarks();
        fillTable();
    }//GEN-LAST:event_btn_sapXepDiemActionPerformed

    private void btn_sapXepTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sapXepTenActionPerformed
        // TODO add your handling code here:
        orderByName();
        fillTable();
    }//GEN-LAST:event_btn_sapXepTenActionPerformed

    private void btn_writeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_writeActionPerformed
        // TODO add your handling code here:
        write();
    }//GEN-LAST:event_btn_writeActionPerformed

    private void btn_readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readActionPerformed
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_btn_readActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanLySinhVien().setVisible(true);
            }
        });
    }
    
    
    public void write() { // ghi file ra dia
        // chon vi tri de luu file
        try {
            JFileChooser fc = new JFileChooser(); // chon la save
            int chon = fc.showSaveDialog(null);
            if(chon == 0) { // cac nut tu trai qua phai se la 0 1 2 3 (0 la save, 1 la cancer);
                String path; // lay duong dan cua file
                path = fc.getSelectedFile().getPath();
                FileOutputStream fo = new FileOutputStream(path); // ghi tu file ra dia
                ObjectOutputStream ofo = new ObjectOutputStream(fo); // ghi doi tuong vao file
                ofo.writeObject(mangHocSinh); // ghi list ra file
                ofo.close(); // dongfile
                JOptionPane.showMessageDialog(this, "Them bang thanh cong");
                
                // xoa table
                DefaultTableModel model = (DefaultTableModel) tbl.getModel();
                model.setRowCount(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ghi file loi!");
        }
        
    }
    
    public void read() {
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showOpenDialog(null);
            if(chon == 0) { // tim thay file de doc
                String path = fc.getSelectedFile().getPath();
                FileInputStream fi = new FileInputStream(path);
                ObjectInputStream ifi = new ObjectInputStream(fi);
                mangHocSinh = (ArrayList<Student>) ifi.readObject(); //ep tu file ra list
                ifi.close();
                fillTable(); // do du lieu ra bang
                JOptionPane.showMessageDialog(this, "Doc thanh cong!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi doc file!");
        }
    }
    
    
    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        
        model.setRowCount(0);
        
        for (Student s : mangHocSinh) {
            model.addRow(new Object[] {
                s.getName(), s.getMarks(), s.getMajor(), s.getGrade(), s.isBonus()
            });
        }
    }
    
    public Student readStudent() { // doc du lieu tu form
        Student sv = new Student();
        sv.setName(txt_hoVaTen.getText());
        sv.setMarks(Double.parseDouble(txt_diem.getText()));
        sv.setMajor(cbo_nganh.getSelectedItem() + ""); // lay ra doi tuong dang duoc chon
        return sv;
    }
    
    public void writeStudent(Student sv) {
        txt_hoVaTen.setText(sv.getName()); // ten
        txt_diem.setText(sv.getMarks() + ""); // diem
        txt_hocLuc.setText(sv.getGrade()); // hoc luc
        for (int i = 0; i < cbo_nganh.getItemCount(); i++) { // chuyen nganh
            if(cbo_nganh.getItemAt(i).equalsIgnoreCase(sv.getMajor())) {
                cbo_nganh.setSelectedIndex(i);
            }
        }
        if(sv.isBonus() == true) {
            chk_phanThuong.setSelected(true);
        }
    }
    
    public void addStudent() {
        mangHocSinh.add(readStudent());
        fillTable();
    }
    
    public int indexTable(){
        return tbl.getSelectedRow();
    }
    
    public void removeStudent() {
        mangHocSinh.remove(indexTable());
        fillTable();
    }
    
    public void updateStudent() {
        mangHocSinh.set(indexTable(), readStudent());
        fillTable();
    }
    
    public void clearForm() {
        txt_diem.setText("");
        txt_hoVaTen.setText("");
        txt_hocLuc.setText("");
        chk_phanThuong.setSelected(false);
    }
    
    public void orderByName() {
        Comparator<Student> com = new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                return o1.getName().compareToIgnoreCase(o2.getName());
            }
        };
        Collections.sort(mangHocSinh, com);
    }
    
    public void orderByMarks() {
        Comparator<Student> com = new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                if(o1.getMarks() > o2.getMarks()) {
                    return 1;
                } else if(o1.getMarks() < o2.getMarks()){
                    return -1;
                } else {
                    return 0;
                }
            }
        };
        Collections.sort(mangHocSinh, com);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_nhapMoi;
    private javax.swing.JButton btn_read;
    private javax.swing.JButton btn_sapXepDiem;
    private javax.swing.JButton btn_sapXepTen;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_write;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbo_nganh;
    private javax.swing.JCheckBox chk_phanThuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_diem;
    private javax.swing.JTextField txt_hoVaTen;
    private javax.swing.JTextField txt_hocLuc;
    // End of variables declaration//GEN-END:variables
}
