package LamLaiLabs3ChoNho;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLySinhVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySinhVien
     */
    public QuanLySinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        txt_diem = new javax.swing.JTextField();
        txt_hocLuc = new javax.swing.JTextField();
        cbo_nganh = new javax.swing.JComboBox<>();
        chk_thuong = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();
        btn_nhapMoi = new javax.swing.JButton();
        btn_sapXepTen = new javax.swing.JButton();
        btn_sapXepDiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUAN LY SINH VIEN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("HO VA TEN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("DIEM");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("NGANH");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("HOC LUC");

        txt_ten.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txt_diem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_diem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diemActionPerformed(evt);
            }
        });
        txt_diem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_diemKeyReleased(evt);
            }
        });

        txt_hocLuc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_hocLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hocLucActionPerformed(evt);
            }
        });

        cbo_nganh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbo_nganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chk_thuong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        chk_thuong.setText("Co phan thuong khong?");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HO VA TEN", "DIEM", "NGANH ", "HOC LUC", "THUONG"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_them.setText("Them");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_xoa.setText("Xoa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_capNhat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_capNhat.setText("Cap nhat");
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });

        btn_nhapMoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_nhapMoi.setText("Nhap moi");
        btn_nhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhapMoiActionPerformed(evt);
            }
        });

        btn_sapXepTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_sapXepTen.setText("Sap xep theo ten");
        btn_sapXepTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sapXepTenActionPerformed(evt);
            }
        });

        btn_sapXepDiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_sapXepDiem.setText("Sap xep theo diem");
        btn_sapXepDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sapXepDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_sapXepTen)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sapXepDiem))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_diem, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                                    .addComponent(txt_ten))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(43, 43, 43)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk_thuong)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_them)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_xoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_capNhat)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_nhapMoi))
                                    .addComponent(cbo_nganh, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_hocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_diem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_nganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(txt_hocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(chk_thuong)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_xoa)
                    .addComponent(btn_capNhat)
                    .addComponent(btn_nhapMoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sapXepTen)
                    .addComponent(btn_sapXepDiem))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_diemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diemActionPerformed

    private void txt_hocLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hocLucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hocLucActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        this.xoaSinhVien();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        // TODO add your handling code here:
        this.capNhat();
    }//GEN-LAST:event_btn_capNhatActionPerformed

    private void btn_nhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhapMoiActionPerformed
        // TODO add your handling code here:
        this.lamMoi();
    }//GEN-LAST:event_btn_nhapMoiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Quan ly sinh vien");
        
        
        cbo_nganh.removeAllItems();
        cbo_nganh.addItem("Cong nghe thong tin");
        cbo_nganh.addItem("Ung dung phan men");
        cbo_nganh.addItem("Thiet ke do hoa");
        cbo_nganh.addItem("Lap trinh may tinh");
        
        Student sv = new Student("Nguyen chi thuan", 9.9, "Cong nghe thong tin");
        mangSinhVien.add(sv);
        fillTable();
    }//GEN-LAST:event_formWindowOpened

    private void btn_sapXepTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sapXepTenActionPerformed
        // TODO add your handling code here:
        this.sapXepTheTen();
        fillTable();
    }//GEN-LAST:event_btn_sapXepTenActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        this.themSinhVien();
    }//GEN-LAST:event_btn_themActionPerformed

    private void txt_diemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_diemKeyReleased
        // TODO add your handling code here:
        
        Student sv = readStudent();
        if(sv.getDiem() > 10) {
            sv.setDiem(10);
            txt_diem.setText("10");
        }
        if(sv.getDiem() < 0) {
            sv.setDiem(0);
            txt_diem.setText("0");
        }
        txt_hocLuc.setText(sv.getHocLuc());
        chk_thuong.setSelected(sv.kiemTraThuong());
    }//GEN-LAST:event_txt_diemKeyReleased

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        writeStudent(mangSinhVien.get(indexTable()));
    }//GEN-LAST:event_tblMouseClicked

    private void btn_sapXepDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sapXepDiemActionPerformed
        // TODO add your handling code here:
        this.sapXepTheoDiem();
        fillTable();
    }//GEN-LAST:event_btn_sapXepDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySinhVien().setVisible(true);
            }
        });
    }
    
    ArrayList<Student> mangSinhVien = new ArrayList<>();
    
    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        
        model.setRowCount(0);
        
        for (Student s : mangSinhVien) {
            model.addRow(new Object[] {
                s.getTen(), s.getDiem(), s.getNganh(), s.getHocLuc(), s.kiemTraThuong()
            });
        }
    }
    
    
    // lay du lieu tu form
    public Student readStudent() { 
        // ta chi can lay ten, diem, nganh
        String ten = txt_ten.getText();
        Double diem = Double.parseDouble(txt_diem.getText());
        String nganh = cbo_nganh.getSelectedItem() + "";
        
        return new Student(ten, diem, nganh);
    }
    
    // doc du lieu vao form
    public void writeStudent(Student sv) {
        txt_ten.setText(sv.getTen());
        txt_diem.setText(sv.getDiem() + "");
        for (int i = 0; i < cbo_nganh.getItemCount(); i++) {
            if(cbo_nganh.getItemAt(i).equalsIgnoreCase(sv.getNganh())) {
                cbo_nganh.setSelectedIndex(i);
            }
        }
        txt_hocLuc.setText(sv.getHocLuc());
        chk_thuong.setSelected(sv.kiemTraThuong());
    }
    
    public void themSinhVien() {
        mangSinhVien.add(readStudent());
        fillTable();
    }
    
    public int indexTable() {
        return tbl.getSelectedRow();
    }
    
    public void xoaSinhVien() {
        mangSinhVien.remove(indexTable());
        this.fillTable();
    }
    
    public void capNhat() {
        mangSinhVien.set(indexTable(), readStudent());
        this.fillTable();
    }
    
    public void lamMoi() {
        txt_ten.setText("");
        txt_diem.setText("");
        txt_hocLuc.setText("");
        chk_thuong.setSelected(false);
    }
    
    public void sapXepTheTen() {
        Collections.sort(mangSinhVien, new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                return o1.getTen().compareToIgnoreCase(o2.getTen());
            }
        });
    }
    
    public void sapXepTheoDiem() {
        Collections.sort(mangSinhVien, new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                if(o1.getDiem() > o2.getDiem()) {
                    return 1;
                } else if(o1.getDiem() < o2.getDiem()) {
                    return -1;
                } else {
                    return 0;
                }
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_nhapMoi;
    private javax.swing.JButton btn_sapXepDiem;
    private javax.swing.JButton btn_sapXepTen;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbo_nganh;
    private javax.swing.JCheckBox chk_thuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_diem;
    private javax.swing.JTextField txt_hocLuc;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables
}
