package fpt.bailabs2_cuahau;

/**
 *
 * @author ASUS
 */
public class Bai5 extends javax.swing.JFrame {

    /**
     * Creates new form Bai5
     */
    public Bai5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        lbl_b = new javax.swing.JLabel();
        txt_b = new javax.swing.JTextField();
        txt_a = new javax.swing.JTextField();
        lbl_phepTinh = new javax.swing.JLabel();
        lbl_ketQua = new javax.swing.JLabel();
        txt_ketQua = new javax.swing.JTextField();
        cbo_phepTinh = new javax.swing.JComboBox<>();
        btn_thucHien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setBackground(new java.awt.Color(51, 51, 255));
        lbl_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(51, 51, 255));
        lbl_title.setText("Tinh Toan");

        lbl_a.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_a.setText("A");

        lbl_b.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_b.setText("B");

        txt_b.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_a.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl_phepTinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_phepTinh.setText("Phep tinh");

        lbl_ketQua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ketQua.setText("Ket qua");

        txt_ketQua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_ketQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ketQuaActionPerformed(evt);
            }
        });

        cbo_phepTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbo_phepTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "+", "*", "/", "%" }));

        btn_thucHien.setBackground(new java.awt.Color(153, 153, 153));
        btn_thucHien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_thucHien.setForeground(new java.awt.Color(51, 51, 255));
        btn_thucHien.setText("Thuc hien");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_a)
                        .addGap(18, 18, 18)
                        .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_phepTinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_phepTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_ketQua)
                        .addGap(18, 18, 18)
                        .addComponent(txt_ketQua, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(13, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(lbl_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btn_thucHien)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_a)
                    .addComponent(lbl_b)
                    .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_phepTinh)
                    .addComponent(lbl_ketQua)
                    .addComponent(txt_ketQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_phepTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btn_thucHien)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ketQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ketQuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ketQuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thucHien;
    private javax.swing.JComboBox<String> cbo_phepTinh;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_b;
    private javax.swing.JLabel lbl_ketQua;
    private javax.swing.JLabel lbl_phepTinh;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_b;
    private javax.swing.JTextField txt_ketQua;
    // End of variables declaration//GEN-END:variables
}
