package BaiTest1;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class CongViecCuaToi extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form CongViecCuaToi
     */
    public CongViecCuaToi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_ten = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_congViec = new javax.swing.JTextField();
        cbo_doanhNghiep = new javax.swing.JComboBox<>();
        rdo_co = new javax.swing.JRadioButton();
        rdo_khong = new javax.swing.JRadioButton();
        txt_thuNhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_tim = new javax.swing.JButton();
        btn_sapXep = new javax.swing.JButton();
        btn_write = new javax.swing.JButton();
        btn_read = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_ten.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_ten.setForeground(new java.awt.Color(0, 0, 255));
        lbl_ten.setText("CONG VIEC CUA TOI   ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("TEN CONG VIEC");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("TEN DOANH NGHIEP");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("HOC  TIEN SY");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("THU NHAP");

        txt_congViec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbo_doanhNghiep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_doanhNghiep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(rdo_co);
        rdo_co.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdo_co.setSelected(true);
        rdo_co.setText("CO");

        buttonGroup1.add(rdo_khong);
        rdo_khong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdo_khong.setText("KHONG");

        txt_thuNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TEN CV", "TEN DN", "HOC TIEN SY", "THU NHAP", "KET LUAN"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_them.setText("THEM");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_sua.setText("SUA");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_xoa.setText("XOA");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_tim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_tim.setText("TIM");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        btn_sapXep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_sapXep.setText("SAP XEP");
        btn_sapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sapXepActionPerformed(evt);
            }
        });

        btn_write.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_write.setText("GHI FILE");
        btn_write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_writeActionPerformed(evt);
            }
        });

        btn_read.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_read.setText("MO FILE");
        btn_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readActionPerformed(evt);
            }
        });

        btn_luu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_luu.setText("LUU");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(lbl_ten))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(100, 100, 100)
                                        .addComponent(txt_thuNhap))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdo_co)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rdo_khong)
                                                .addGap(35, 35, 35))
                                            .addComponent(txt_congViec)
                                            .addComponent(cbo_doanhNghiep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_tim, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_sua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_them, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_write, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_read, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_sapXep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_luu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ten)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_congViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them)
                    .addComponent(btn_sapXep))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbo_doanhNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua)
                    .addComponent(btn_write))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdo_co)
                    .addComponent(rdo_khong)
                    .addComponent(btn_xoa)
                    .addComponent(btn_read))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_thuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim)
                    .addComponent(btn_luu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        // TODO add your handling code here:
        timCongViec();
    }//GEN-LAST:event_btn_timActionPerformed

    private void btn_sapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sapXepActionPerformed
        // TODO add your handling code here:
        sapxep();
        JOptionPane.showMessageDialog(this, "Sap xep theo thu nhap!");
    }//GEN-LAST:event_btn_sapXepActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        cbo_doanhNghiep.removeAllItems();
        cbo_doanhNghiep.addItem("FPT");
        cbo_doanhNghiep.addItem("Oppo");
        cbo_doanhNghiep.addItem("Iphone");
        cbo_doanhNghiep.addItem("SumSung");
    }//GEN-LAST:event_formWindowOpened

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        writeForm(list.get(indexTable()));
    }//GEN-LAST:event_tblMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        update();
        JOptionPane.showMessageDialog(this, "Update mot job");
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        delete();
        JOptionPane.showMessageDialog(this, "Delete mot job");
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        this.add();
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_writeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_writeActionPerformed
        // TODO add your handling code here:
        write();
    }//GEN-LAST:event_btn_writeActionPerformed

    private void btn_readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readActionPerformed
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_btn_readActionPerformed

    //----------------------------------------------------------------------
    ArrayList<MyJob> list = new ArrayList<>();

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongViecCuaToi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongViecCuaToi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongViecCuaToi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongViecCuaToi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        CongViecCuaToi cv = new CongViecCuaToi();
        cv.setVisible(true);
        Thread th = new Thread(cv);
        th.start();
    }

    @Override
    public void run() {
        while (true) {
            String ten = lbl_ten.getText();
            String dau = ten.substring(0, 1);
            ten = ten.substring(1) + dau;

            lbl_ten.setText(ten);

            try {
                Thread.sleep(1000);
            } catch (Exception e) {
            }
        }
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);

        for (MyJob myJob : list) {
            model.addRow(new Object[]{
                myJob.getCongViec(), myJob.getDoanhNghiep(), myJob.getHocTienSi(),
                myJob.getThuNhap(), myJob.getKetLuan()
            });
        }
    }

    public MyJob readForm() {
        MyJob job = new MyJob();
        job.setCongViec(txt_congViec.getText());
        job.setThuNhap(Double.parseDouble(txt_thuNhap.getText()));

        if (rdo_co.isSelected()) {
            job.setHocTienSi("Co");
        } else {
            job.setHocTienSi("Khong");
        }

        job.setDoanhNghiep(cbo_doanhNghiep.getSelectedItem() + "");

        return job;
    }

    public void writeForm(MyJob job) {
        txt_congViec.setText(job.getCongViec());
        txt_thuNhap.setText(job.getThuNhap() + "");

        if (job.getHocTienSi().equalsIgnoreCase("Co")) {
            rdo_co.setSelected(true);
        } else {
            rdo_khong.setSelected(true);
        }

        for (int i = 0; i < cbo_doanhNghiep.getItemCount(); i++) {
            if (cbo_doanhNghiep.getItemAt(i).equalsIgnoreCase(job.getDoanhNghiep())) {
                cbo_doanhNghiep.setSelectedIndex(i);
                break;
            }
        }
    }

    public int indexTable() {
        return tbl.getSelectedRow();
    }

    public void add() {
        if (kiemTraCongViec() == false) {
            txt_congViec.setBackground(Color.YELLOW);
            txt_congViec.requestFocus();
        } else if (kiemTraThuNhap()== false) {
            txt_thuNhap.setBackground(Color.YELLOW);
            txt_thuNhap.requestFocus();
        } else {
            list.add(readForm());
            JOptionPane.showMessageDialog(this, "Luu mot job");
            fillTable();
        }
    }
    
    //------------------------------------------------------
    public boolean kiemTraCongViec() {
        String dinhDang = "[a-zA-Z ]+";
        if (txt_congViec.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cong viec null!");
            return false;
        } else if (txt_congViec.getText().matches(dinhDang) == false) {
            JOptionPane.showMessageDialog(this, "Khong dung dinh dang chu!");
            return false;
        }
        txt_congViec.setBackground(Color.WHITE);
        return true;
    }

    
    public boolean kiemTraThuNhap() {
        double thuNhap;
        if (txt_thuNhap.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Thu nhap null!");
            return false;
        } else {
            try {
                thuNhap = Double.parseDouble(txt_thuNhap.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Khong dung dinh dang so!");
                return false;
            }
        }
        if (thuNhap < 0) {
            JOptionPane.showMessageDialog(this, "Thu nhap lon hon 0!");
            return false;
        }

        txt_thuNhap.setBackground(Color.WHITE);
        return true;
    }

    //------------------------------------------------------
    public void update() {
        list.set(indexTable(), readForm());
        fillTable();
    }

    public void delete() {
        list.remove(indexTable());
        fillTable();
    }

    public void clearForm() {
        txt_congViec.setText("");
        txt_thuNhap.setText("");
        rdo_co.setSelected(true);
        cbo_doanhNghiep.setSelectedItem(0);
    }
    
    public void timCongViec() {
        String tam = JOptionPane.showInputDialog("Tim the ten cong viec!");
        String tenCongViec = tam;
        for (int i = 0; i < list.size(); i++) {
            if(tenCongViec.equalsIgnoreCase(list.get(i).getCongViec())) {
                writeForm(list.get(i));
                tbl.setRowSelectionInterval(i, i);
            }
        }
    }

    public void sapxep() {
        Collections.sort(list, new Comparator<MyJob>() {
            @Override
            public int compare(MyJob o1, MyJob o2) {
                if (o1.getThuNhap() > o2.getThuNhap()) {
                    return 1;
                } else if (o1.getThuNhap() < o2.getThuNhap()) {
                    return -1;
                } else {
                    return 0;
                }
            }
        });

        fillTable();
    }
    
    public void write() { // ghi file ra dia
        // chon vi tri de luu file
        try {
            JFileChooser fc = new JFileChooser(); // chon la save
            int chon = fc.showSaveDialog(null);
            if(chon == 0) { // cac nut tu trai qua phai se la 0 1 2 3 (0 la save, 1 la cancer);
                String path; // lay duong dan cua file
                path = fc.getSelectedFile().getPath();
                FileOutputStream fo = new FileOutputStream(path); // ghi tu file ra dia
                ObjectOutputStream ofo = new ObjectOutputStream(fo); // ghi doi tuong vao file
                ofo.writeObject(list); // ghi list ra file
                ofo.close(); // dongfile
                JOptionPane.showMessageDialog(this, "Them bang thanh cong");
                
                // xoa table
                DefaultTableModel model = (DefaultTableModel) tbl.getModel();
                model.setRowCount(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ghi file loi!");
        }
        
    }
    
    public void read() {
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showOpenDialog(null);
            if(chon == 0) { // tim thay file de doc
                String path = fc.getSelectedFile().getPath();
                FileInputStream fi = new FileInputStream(path);
                ObjectInputStream ifi = new ObjectInputStream(fi);
                list = (ArrayList<MyJob>) ifi.readObject(); //ep tu file ra list
                ifi.close();
                fillTable(); // do du lieu ra bang
                JOptionPane.showMessageDialog(this, "Doc thanh cong!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi doc file!");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_read;
    private javax.swing.JButton btn_sapXep;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_write;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_doanhNghiep;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ten;
    private javax.swing.JRadioButton rdo_co;
    private javax.swing.JRadioButton rdo_khong;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_congViec;
    private javax.swing.JTextField txt_thuNhap;
    // End of variables declaration//GEN-END:variables
}
