package BaiTest3;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ThanYeuMe extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form ThanYeuMe
     */
    public ThanYeuMe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_tieuDe = new javax.swing.JLabel();
        lbl_thoiGian = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_ngaySinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbo_queQuan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rdoA = new javax.swing.JRadioButton();
        rdoB = new javax.swing.JRadioButton();
        rdoAB = new javax.swing.JRadioButton();
        rdoO = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        lbl_thoiGianChay = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_tieuDe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_tieuDe.setForeground(new java.awt.Color(51, 0, 255));
        lbl_tieuDe.setText("THAN YEU ME   ");

        lbl_thoiGian.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_thoiGian.setForeground(new java.awt.Color(255, 153, 0));
        lbl_thoiGian.setText("THOI GIAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("HO TEN");

        txt_hoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("NGAY SINH");

        txt_ngaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("QUE QUAN");

        cbo_queQuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_queQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("NHOM MAU");

        buttonGroup1.add(rdoA);
        rdoA.setSelected(true);
        rdoA.setText("A");

        buttonGroup1.add(rdoB);
        rdoB.setText("B");

        buttonGroup1.add(rdoAB);
        rdoAB.setText("AB");

        buttonGroup1.add(rdoO);
        rdoO.setText("O");

        btnThem.setText("THEM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnTim.setText("TIM");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnDoc.setText("DOC FILE");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        btnGhi.setText("GHI FILE");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnThoat.setText("THOAT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        lbl_thoiGianChay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_thoiGianChay.setForeground(new java.awt.Color(204, 0, 0));
        lbl_thoiGianChay.setText("THOI GIAN CHAY");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HO TEN", "NGAY SINH", "QUE QUAN", "NHOM MAU"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tieuDe)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbo_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(lbl_thoiGianChay)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_thoiGian))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoA)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoB)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoAB)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoO))
                                    .addComponent(txt_hoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                    .addComponent(txt_ngaySinh)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnTim)
                                .addGap(18, 18, 18)
                                .addComponent(btnDoc)
                                .addGap(18, 18, 18)
                                .addComponent(btnGhi)
                                .addGap(18, 18, 18)
                                .addComponent(btnThoat))
                            .addComponent(jScrollPane1))
                        .addGap(0, 35, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tieuDe)
                    .addComponent(lbl_thoiGian)
                    .addComponent(lbl_thoiGianChay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbo_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdoA)
                    .addComponent(rdoB)
                    .addComponent(rdoAB)
                    .addComponent(rdoO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnTim)
                    .addComponent(btnDoc)
                    .addComponent(btnGhi)
                    .addComponent(btnThoat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        cbo_queQuan.removeAllItems();
        cbo_queQuan.addItem("Ha Noi");
        cbo_queQuan.addItem("Thai Binh");
        cbo_queQuan.addItem("Ho Chi Minh");
        cbo_queQuan.addItem("Da Nang");

        Mami m1 = new Mami("Thuan", "20/10/2003", "Ha Noi", "O");
        Mami m2 = new Mami("Ngoc", "5/6/2006", "Ho Chi Minh", "A");
        Mami m3 = new Mami("Binh", "21/1/2001", "Da Nang", "B");
        Mami m4 = new Mami("Viet Anh", "2/11/2004", "Thai Binh", "AB");

        list.add(m1);
        list.add(m2);
        list.add(m3);
        list.add(m4);

        fillTable();

        tbl.setRowSelectionInterval(1, 1);

        startTime = System.currentTimeMillis() / 1000;
    }//GEN-LAST:event_formWindowOpened

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        them();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        writeForm(list.get(indexTable()));
    }//GEN-LAST:event_tblMouseClicked

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        // TODO add your handling code here:
        write();
    }//GEN-LAST:event_btnDocActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_btnTimActionPerformed

    //-------------------------------------------Main----------------------------------------------
    ArrayList<Mami> list = new ArrayList<>();
    long startTime, endTime;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanYeuMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanYeuMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanYeuMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanYeuMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ThanYeuMe me = new ThanYeuMe();

        me.setVisible(true);

        Thread th1 = new Thread(me);

        th1.start();
    }

    @Override
    public void run() {
        while (true) {
            String chuoi = lbl_tieuDe.getText();
            String dau = chuoi.substring(0, 1);
            chuoi = chuoi.substring(1) + dau;
            lbl_tieuDe.setText(chuoi);

            SimpleDateFormat fm = new SimpleDateFormat("hh:mm:ss a");
            Date date = new Date();
            String thoiGian = fm.format(date);
            lbl_thoiGian.setText(thoiGian);

            endTime = System.currentTimeMillis() / 1000;

            lbl_thoiGianChay.setText("Thoi gian: " + (endTime - startTime));

            try {
                Thread.sleep(1000);
            } catch (Exception e) {
            }
        }
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        for (Mami mami : list) {
            model.addRow(new Object[]{
                mami.getHoten(), mami.getNgaySinh(), mami.getQueQuan(), mami.getNhomMau()
            });
        }
    }

    public Mami readForm() {
        Mami m = new Mami();

        m.setHoten(txt_hoTen.getText());
        m.setNgaySinh(txt_ngaySinh.getText());

        if (rdoA.isSelected()) {
            m.setNhomMau("A");
        } else if (rdoB.isSelected()) {
            m.setNhomMau("B");
        } else if (rdoAB.isSelected()) {
            m.setNhomMau("AB");
        } else {
            m.setNhomMau("O");
        }

        m.setQueQuan(cbo_queQuan.getSelectedItem() + "");

        return m;
    }

    public void writeForm(Mami m) {
        txt_hoTen.setText(m.getHoten());
        txt_ngaySinh.setText(m.getNgaySinh());

        if (m.getNhomMau().equalsIgnoreCase("A")) {
            rdoA.setSelected(true);
        } else if (m.getNhomMau().equalsIgnoreCase("B")) {
            rdoB.setSelected(true);
        } else if (m.getNhomMau().equalsIgnoreCase("AB")) {
            rdoAB.setSelected(true);
        } else {
            rdoO.setSelected(true);
        }

        for (int i = 0; i < cbo_queQuan.getItemCount(); i++) {
            if (cbo_queQuan.getItemAt(i).equalsIgnoreCase(m.getQueQuan())) {
                cbo_queQuan.setSelectedIndex(i);
                break;
            }
        }
    }

    public void them() {
        if (kiemTraTen() == false) {
            txt_hoTen.setBackground(Color.YELLOW);
            txt_hoTen.requestFocus();
        } else if (kiemTraNgaySinh() == false) {
            txt_ngaySinh.setBackground(Color.YELLOW);
            txt_ngaySinh.requestFocus();
        } else {
            list.add(readForm());
            fillTable();
            JOptionPane.showMessageDialog(this, "Them thanh cong!");
        }

    }

    public boolean kiemTraTen() {
        String kiemTra = "[a-zA-z ]+";
        if (txt_hoTen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ten null!");
            return false;
        } else if (txt_hoTen.getText().matches(kiemTra) == false) {
            JOptionPane.showMessageDialog(this, "Ten khong dung dinh dang!!");
            return false;
        }

        txt_hoTen.setBackground(Color.WHITE);
        return true;
    }

    public boolean kiemTraNgaySinh() {
        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");

        if (txt_ngaySinh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ngay sinh null!");
            return false;
        } else {
            try {
                Date date = fm.parse(txt_ngaySinh.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ngay sinh sai dinh dang!");
                return false;
            }
        }
        txt_ngaySinh.setBackground(Color.WHITE);
        return true;
    }

    public int indexTable() {
        return tbl.getSelectedRow();
    }

    public void write() {
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showSaveDialog(this);
            if (chon == 0) {
                String path = fc.getSelectedFile().getPath();

                FileOutputStream fo = new FileOutputStream(path);

                ObjectOutputStream ofo = new ObjectOutputStream(fo);

                ofo.writeObject(list);

                ofo.close();

                DefaultTableModel model = (DefaultTableModel) tbl.getModel();
                model.setRowCount(0);

                JOptionPane.showMessageDialog(this, "Ghi file thanh cong!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi ghi file!");
        }

    }
    
    public void timKiem() {
        int count = 0;
        String tam = JOptionPane.showInputDialog("Tim kiem the que quan");
        
        for (int i = 0; i < list.size(); i++) {
            if(list.get(i).getQueQuan().equalsIgnoreCase(tam)) {
                writeForm(list.get(i));
                tbl.setRowSelectionInterval(i, i);
                count = 1;
                return;
            }
        }
        
        if(count == 1) {
            JOptionPane.showMessageDialog(this, "Da tim thay");
        } else {
            JOptionPane.showMessageDialog(this, "Khong tim thay");
        }
    }

    public void read() {
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showSaveDialog(this);
            if (chon == 0) {
                String path = fc.getSelectedFile().getPath();
                FileInputStream fi = new FileInputStream(path);
                
                ObjectInputStream ifi = new ObjectInputStream(fi);
                
                list = (ArrayList<Mami>) ifi.readObject();
                
                ifi.close();
                
                fillTable();
                
                JOptionPane.showMessageDialog(this, "Doc file thanh cong!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Doc ghi file!");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_queQuan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_thoiGian;
    private javax.swing.JLabel lbl_thoiGianChay;
    private javax.swing.JLabel lbl_tieuDe;
    private javax.swing.JRadioButton rdoA;
    private javax.swing.JRadioButton rdoAB;
    private javax.swing.JRadioButton rdoB;
    private javax.swing.JRadioButton rdoO;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_ngaySinh;
    // End of variables declaration//GEN-END:variables
}
