package thread;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author ASUS
 */
public class ChayChu extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form ChayChu
     */
    public ChayChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ten = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_time2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_ten.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_ten.setForeground(new java.awt.Color(255, 0, 102));
        lbl_ten.setText("NGUYEN CHI THUAN ");

        lbl_time.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 0, 102));

        lbl_time2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_time2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_ten)
                        .addGap(62, 62, 62)
                        .addComponent(lbl_time)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ten)
                    .addComponent(lbl_time))
                .addGap(74, 74, 74)
                .addComponent(lbl_time2)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        ts = Calendar.getInstance().getTimeInMillis() / 1000;
        ts = System.currentTimeMillis() / 1000;
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChayChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChayChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChayChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChayChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChayChu().setVisible(true);
//            }
//        });

        ChayChu dt = new ChayChu(); // tao doi tuong cua form
        
        dt.setVisible(true); // hien ra form
        
        Thread th = new Thread(dt); // tao thread
        
        th.start();
    }
    
    long ts, te; // thoi gian bat dau va thoi gian ket thuc

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_ten;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_time2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        String ten;
        while (true) {
            ten = lbl_ten.getText(); // lay ten
            
            // c la ki tu dau tien
            // cat lay ky tu dau tien
            String c = ten.substring(0, 1);
            
            // cat phan con lai + chu cai dau
            ten = ten.substring(1) + c;
            
            lbl_ten.setText(ten);// gan lai vao lbl
            
            
            // ------------------------------------------------------
            
            // thoi gian
            SimpleDateFormat d = new SimpleDateFormat("dd-MM-yyyy; hh:mm:ss; a");
            
            Date date = new Date();
            
            String t = d.format(date); 
            // format date theo mau ben tren
            
            lbl_time.setText(t); // gan lai vao lbl
            
            // -------------------------------------------------------
            
            // thoi gian da chay chuong trinh
            // thoi gian hien tai
//            te = Calendar.getInstance().getTimeInMillis()/1000;
            te = System.currentTimeMillis() / 1000;
            lbl_time2.setText("Thoi gian da chay: " + (te - ts));


            
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
                
            }
                    
        }
    }
}
