package bai4;

import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class bai4_labs2 extends javax.swing.JFrame {

    /**
     * Creates new form bai4_labs2
     */
    public bai4_labs2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbl_tieuDe = new javax.swing.JLabel();
        tablePane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_passWord = new javax.swing.JLabel();
        txt_passWord = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        lbl_role = new javax.swing.JLabel();
        chk_user = new javax.swing.JCheckBox();
        chk_admin = new javax.swing.JCheckBox();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_user = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_tieuDe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_tieuDe.setForeground(new java.awt.Color(0, 51, 204));
        lbl_tieuDe.setText("USE MANAGEMENT");

        lbl_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_name.setText("Username");

        lbl_passWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_passWord.setText("Password");

        txt_passWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl_role.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_role.setText("Role");

        buttonGroup1.add(chk_user);
        chk_user.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chk_user.setText("User");

        buttonGroup1.add(chk_admin);
        chk_admin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chk_admin.setSelected(true);
        chk_admin.setText("Admin");

        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_remove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_passWord)
                            .addComponent(lbl_name)
                            .addComponent(lbl_role))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_add)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_passWord, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chk_user, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(chk_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btn_remove)
                                .addGap(39, 39, 39)
                                .addComponent(btn_update)))
                        .addGap(34, 34, 34)
                        .addComponent(btn_reset)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_passWord)
                    .addComponent(txt_passWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_role)
                    .addComponent(chk_user)
                    .addComponent(chk_admin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_remove)
                    .addComponent(btn_update)
                    .addComponent(btn_reset))
                .addGap(21, 21, 21))
        );

        tablePane.addTab("EXITION", jPanel1);

        tbl_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "user name", "pass word", "Role"
            }
        ));
        tbl_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_user);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablePane.addTab("LIST", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tieuDe)
                    .addComponent(tablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_tieuDe)
                .addGap(26, 26, 26)
                .addComponent(tablePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Ham khi bat cua so thi no se duoc chay dung 1 lam
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // tao 3 doi tuong
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        User u1 = new User("a1", "11111", "user");
        User u2 = new User("a2", "22222", "user");
        User u3 = new User("a3", "33333", "admin");
        ListUser.add(u1);
        ListUser.add(u2);
        ListUser.add(u3);
        this.fillTable();
    }//GEN-LAST:event_formWindowOpened

    // khi an cao add thi them mot doi tuong vao list
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        // Lay du lieu tu form cho vao list
        // do vao table

        this.addUser(); // lay du lieu tu form cho vao list
        this.fillTable();
        JOptionPane.showMessageDialog(this, "Ban da them User");
    }//GEN-LAST:event_btn_addActionPerformed

    // khi an vao nut remove thi no xoa
    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        removeUser();   
        JOptionPane.showMessageDialog(this, "Ban da xoa thanh cong!");
    }//GEN-LAST:event_btn_removeActionPerformed

    // tao su kien onclick cho bang
    private void tbl_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_userMouseClicked
        // TODO add your handling code here:
        int user = readTable();

        // doc du lieu vao form
        this.writeForm(ListUser.get(user));

    }//GEN-LAST:event_tbl_userMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        updateUser();
        JOptionPane.showMessageDialog(this, "Ban da update thanh cong!");
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai4_labs2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai4_labs2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai4_labs2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai4_labs2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai4_labs2().setVisible(true);
            }
        });
    }

    ArrayList<User> ListUser = new ArrayList<>(); // khai bao list de chua cac gia tri

    // tao ham fillTale
    public void fillTable() {
        // khai bao model lay ra bang
        DefaultTableModel mol = (DefaultTableModel) tbl_user.getModel(); // bat buoc phai thuoc

        // xoa du lieu cu cua bang
        mol.setRowCount(0);

        // fill du lieu vao bang
        for (User x : ListUser) {
            Object[] data = new Object[]{
                x.getUserName(), x.getPassWord(), x.getRole()
            };
            mol.addRow(data);
        }
    }

    public User readForm() {
        String ten = txt_name.getText();
        String pass = txt_passWord.getText();
        String role;
        // lay checkbok giong y nhu radio
        if (chk_user.isSelected()) {  // user duoc chon  
            role = "User";
        } else {
            role = "Admin";
        }
        User user = new User(ten, pass, role);
        return user;
    }

    public void writeForm(User user) {
        txt_name.setText(user.getUserName());
        txt_passWord.setText(user.getPassWord());
        // hien thi len check giong nhu radio
        if (user.getRole().equalsIgnoreCase("User")) { // co nghia la user duoc chon
            chk_user.setSelected(true);
        } else {
            chk_admin.setSelected(true);
        }
    }

    // tao user tu form va them vao List<>
    public void addUser() {
        ListUser.add(readForm());
        // readForm(): la phuong thuc lay ra 1 doi tuong user tu form
    }

    // xoa trang form
    public void clearForm() {
        txt_name.setText("");
        txt_passWord.setText("");
    }

    // lay doi tuong tu table dat sang form
    public int readTable() {
        int index;
        index = tbl_user.getSelectedRow(); // chon hang nao thi no se tra ve index
        // index cua table == voi index cua listUser
        // lay ra doi tuong user tia vi tri index

        
        // tao bien tao de tuy bien luc chan thi doi no ve doi tuong
        User tam = ListUser.get(index);
        
        
        return index;
    }

    // xoa user khoi list<>
    public void removeUser() {
        // xoa list
        
        ListUser.remove(readTable());

        // cap nhat lai bang
        this.fillTable();
    }
    
    public void updateUser() {
        ListUser.set(readTable(), readForm());
        
        // cap nhap lai bang
        this.fillTable();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chk_admin;
    private javax.swing.JCheckBox chk_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_passWord;
    private javax.swing.JLabel lbl_role;
    private javax.swing.JLabel lbl_tieuDe;
    private javax.swing.JTabbedPane tablePane;
    private javax.swing.JTable tbl_user;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_passWord;
    // End of variables declaration//GEN-END:variables
}
