package Bai3;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ComboBox extends javax.swing.JFrame {

    /**
     * Creates new form ComboBox
     */
    public ComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbo_queQuan = new javax.swing.JComboBox<>();
        btn_chon = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        txt_them = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("DEMO COMBO BOX");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("QUE QUAN");

        cbo_queQuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbo_queQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_queQuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbo_queQuanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbo_queQuanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbo_queQuanMouseReleased(evt);
            }
        });
        cbo_queQuan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbo_queQuanPropertyChange(evt);
            }
        });

        btn_chon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_chon.setText("CHON");
        btn_chon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonActionPerformed(evt);
            }
        });

        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_them.setText("THEM");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        txt_them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_them, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jLabel2)
                            .addGap(95, 95, 95)
                            .addComponent(cbo_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(btn_chon)
                            .addGap(102, 102, 102)
                            .addComponent(btn_them))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbo_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_chon)
                    .addComponent(btn_them))
                .addGap(38, 38, 38)
                .addComponent(txt_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // B1: xóa các items mac dinh;
        // B2: them ca items cua nguoi dung;

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

        cbo_queQuan.removeAllItems(); // xoa het cac item mac dinh
        cbo_queQuan.addItem("Ha Noi");
        cbo_queQuan.addItem("Hai Phong");
        cbo_queQuan.addItem("Nam Dinh");
        cbo_queQuan.addItem("Ho Chi Minh");
        cbo_queQuan.addItem("Bac Giang");
    }//GEN-LAST:event_formWindowOpened

    //----------------------------------------------------

    private void cbo_queQuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbo_queQuanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_queQuanMouseClicked

    private void cbo_queQuanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbo_queQuanMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_queQuanMouseReleased

    private void cbo_queQuanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbo_queQuanMousePressed
        // TODO add your handling code here:s
    }//GEN-LAST:event_cbo_queQuanMousePressed

    private void cbo_queQuanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbo_queQuanPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_queQuanPropertyChange

    //----------------------------------------------------

    private void btn_chonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonActionPerformed
        // TODO add your handling code here:
        String tam;

        // C1:
//         tam = cbo_queQuan.getSelectedItem() + ""; // lay ra mot doi tuong
        // C2:
        int index = cbo_queQuan.getSelectedIndex();
        tam = cbo_queQuan.getItemAt(index);
        JOptionPane.showMessageDialog(this, tam);
    }//GEN-LAST:event_btn_chonActionPerformed


    private void txt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_themActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_themActionPerformed


    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        
        int i = 0; // kiem tra neu da co thi khong them vao
        String kiemTra = txt_them.getText();
        for (int j = 0; j < cbo_queQuan.getItemCount(); j++) {
            if(kiemTra.equalsIgnoreCase(cbo_queQuan.getItemAt(j))) {
                i++;
            }
        }
        
        if (i == 0) {
            cbo_queQuan.addItem(txt_them.getText());
            txt_them.setText("");
            JOptionPane.showMessageDialog(this, "Ban da them mot Item");
        } else {
            JOptionPane.showMessageDialog(this, "Da co!");
        }
    }//GEN-LAST:event_btn_themActionPerformed


    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chon;
    private javax.swing.JButton btn_them;
    private javax.swing.JComboBox<String> cbo_queQuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_them;
    // End of variables declaration//GEN-END:variables
}
