package BaiTest4;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class BaiTapHangXe extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form BaiTapHangXe
     */
    public BaiTapHangXe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_tieuDe = new javax.swing.JLabel();
        lbl_thoiGian = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_thuNhap = new javax.swing.JTextField();
        cbo_hangXe = new javax.swing.JComboBox<>();
        btnGhi = new javax.swing.JButton();
        btnMo = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_tieuDe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_tieuDe.setForeground(new java.awt.Color(51, 0, 204));
        lbl_tieuDe.setText("MY DREAM   ");

        lbl_thoiGian.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_thoiGian.setForeground(new java.awt.Color(51, 0, 204));
        lbl_thoiGian.setText("Thoi gian");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("HO TEN");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("EMAIL");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("HANG XE OTO");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("THU NHAP");

        txt_hoTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txt_thuNhap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        cbo_hangXe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbo_hangXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGhi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnGhi.setText("GHI FILE");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnMo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMo.setText("MO FILE");
        btnMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnTimKiem.setText("TIM KIEM");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HO TEN", "EMAIL", "HANG XE OTO", "THU NHAP"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnGhi)
                .addGap(66, 66, 66)
                .addComponent(btnMo)
                .addGap(59, 59, 59)
                .addComponent(btnTimKiem)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_thuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(132, 132, 132)
                                .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(86, 86, 86)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbo_hangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tieuDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_thoiGian)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tieuDe)
                    .addComponent(lbl_thoiGian))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbo_hangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_thuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGhi)
                    .addComponent(btnMo)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);

        cbo_hangXe.removeAllItems();
        cbo_hangXe.addItem("BMW");
        cbo_hangXe.addItem("MES");
        cbo_hangXe.addItem("TOROTA");

        HangXe h1 = new HangXe("Nguyen Chi Thuan", "thuan@gmai.com", "BMW", 210);
        HangXe h2 = new HangXe("Nguyen The Ngoc", "ngoc@gmai.com", "MES", 21);
        HangXe h3 = new HangXe("Nguyen Van Binh", "binh@gmai.com", "TOROTA", 11);
        HangXe h4 = new HangXe("Phan Quang Huy", "huy@gmai.com", "MES", 23);

        list.add(h1);
        list.add(h2);
        list.add(h3);
        list.add(h4);

        fillTable();

        tbl.setRowSelectionInterval(2, 2);
        writeForm(list.get(2));
        
        start = System.currentTimeMillis() / 1000;
    }//GEN-LAST:event_formWindowOpened

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        writeForm(list.get(indexTable()));
    }//GEN-LAST:event_tblMouseClicked

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        // TODO add your handling code here:
        write();
    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoActionPerformed
        // TODO add your handling code here:
        read();
    }//GEN-LAST:event_btnMoActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        timKiemTheTen();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    //-----------------------------------------main--------------------------------------------------
    ArrayList<HangXe> list = new ArrayList<>();
    long end, start;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaiTapHangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaiTapHangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaiTapHangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaiTapHangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        BaiTapHangXe hang = new BaiTapHangXe();
        hang.setVisible(true);
        Thread th = new Thread(hang);
        th.start();
    }

    @Override
    public void run() {
        while (true) {
            String ten = lbl_tieuDe.getText().toString();
            String dau = ten.substring(0, 1);
            ten = ten.substring(1) + dau;
            lbl_tieuDe.setText(ten);

            end = System.currentTimeMillis() / 1000;
            int tong = (int) (end - start);
            int h, m, s;
            h = tong / 3600;
            m = tong % 3600;
            s = m % 60;
            m = m / 60;
            String t1 ="Thoi gian chay: " +  h + ":" + m + ":" + s;
            lbl_thoiGian.setText(t1);
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
            }
        }
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        model.setRowCount(0);

        for (HangXe hangXe : list) {
            model.addRow(new Object[]{
                hangXe.getHoten(), hangXe.getEmail(), hangXe.getHangXe(), hangXe.getThuNhap()
            });
        }
    }

    public void writeForm(HangXe hangXe) {
        txt_hoTen.setText(hangXe.getHoten());
        txt_email.setText(hangXe.getEmail());
        txt_thuNhap.setText(hangXe.getThuNhap() + "");

        for (int i = 0; i < cbo_hangXe.getItemCount(); i++) {
            if (cbo_hangXe.getItemAt(i).equalsIgnoreCase(hangXe.getHangXe())) {
                cbo_hangXe.setSelectedIndex(i);
                break;
            }
        }
    }

    public int indexTable() {
        return tbl.getSelectedRow();
    }

    public void write() {
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showSaveDialog(this);
            if (chon == 0) {
                String path = fc.getSelectedFile().getPath();
                FileOutputStream fo = new FileOutputStream(path);
                ObjectOutputStream ofo = new ObjectOutputStream(fo);
                ofo.writeObject(list);

                ofo.close();
                DefaultTableModel model = (DefaultTableModel) tbl.getModel();
                model.setRowCount(0);
                JOptionPane.showMessageDialog(this, "Ghi file thanh cong!");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi ghi file!");
        }
    }

    public void read() {
        try {
            JFileChooser fc = new JFileChooser();
            int chon = fc.showSaveDialog(this);
            if (chon == 0) {
                String path = fc.getSelectedFile().getPath();
                FileInputStream fi = new FileInputStream(path);
                ObjectInputStream ifi = new ObjectInputStream(fi);

                list = (ArrayList<HangXe>) ifi.readObject();
                fillTable();

                JOptionPane.showMessageDialog(this, "Doc file thanh cong!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi doc file!");
        }
    }

    public HangXe readForm() {
        return new HangXe();
    }

    public void them() {
        if (kiemTraTen() == false) {
            txt_hoTen.requestFocus();
        } else if (kiemTraEmail() == false) {
            txt_email.requestFocus();
        } else if (kiemTraThuNhap() == false) {
            txt_thuNhap.requestFocus();
        } else {
            list.add(readForm());
            fillTable();
        }
    }

    public boolean kiemTraTen() {
        String dinhDang = "[a-zA-Z ]+";
        if (txt_email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ho ten null!");
            return false;
        } else if (txt_email.getText().matches(dinhDang) == false) {
            JOptionPane.showMessageDialog(this, "Khong dung dinh dang ho ten!");
            return false;
        }
        return true;
    }

    public boolean kiemTraEmail() {
        if (txt_thuNhap.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email null!");
            return false;
        }

        return true;
    }

    public boolean kiemTraThuNhap() {
        Double so = Double.parseDouble(txt_thuNhap.getText());
        if (txt_thuNhap.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Thu nhap null!");
            return false;
        } else if (so <= 10) {
            JOptionPane.showMessageDialog(this, "Thu nhap nho hon 10!");
            return false;
        }

        return true;
    }

    public void timKiemTheTen() {
        String tam = JOptionPane.showInputDialog("Nhap ten muon tim!");
        for (int i = 0; i < list.size(); i++) {
            if (tam.equalsIgnoreCase(list.get(i).getHoten())) {
                writeForm(list.get(i));
                tbl.setRowSelectionInterval(i, i);
                JOptionPane.showMessageDialog(this, "Tim thanh cong!");
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnMo;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbo_hangXe;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_thoiGian;
    private javax.swing.JLabel lbl_tieuDe;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_thuNhap;
    // End of variables declaration//GEN-END:variables
}
