package assignment;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLySinhVien extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form QuanLySinhVien
     */
    public QuanLySinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tuoi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_luong = new javax.swing.JTextField();
        btn_veDau = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_veCuoi = new javax.swing.JButton();
        lbl_hienThi = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_open = new javax.swing.JButton();
        btn_find = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        lbl_time = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("QUAN LY SINH VIEN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("MA NHAN VIEN");

        txt_ma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maActionPerformed(evt);
            }
        });
        txt_ma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_maKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("HO VA TEN");

        txt_hoten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hotenActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("TUOI");

        txt_tuoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_tuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tuoiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("EMAIL");

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("LUONG");

        txt_luong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_luong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_luongActionPerformed(evt);
            }
        });

        btn_veDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_veDau.setText("|<");
        btn_veDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_veDauActionPerformed(evt);
            }
        });

        btn_back.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_back.setText("<<");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_next.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_next.setText(">>");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_veCuoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_veCuoi.setText(">|");
        btn_veCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_veCuoiActionPerformed(evt);
            }
        });

        lbl_hienThi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_hienThi.setForeground(new java.awt.Color(255, 0, 51));
        lbl_hienThi.setText("jLabel7");

        btn_exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_open.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_open.setText("OPEN");
        btn_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openActionPerformed(evt);
            }
        });

        btn_find.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_find.setText("FIND");
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_new.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_new.setText("NEW");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MA", "HO TEN", "TUOI", "EMAIL", "LUONG"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        lbl_time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 0, 0));
        lbl_time.setText("Thoi Gian");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(79, 79, 79)
                                .addComponent(txt_email))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(88, 88, 88)
                                .addComponent(txt_tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_luong, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_veDau, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_veCuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_hienThi))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(47, 47, 47)
                                .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_find, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_open, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_new, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_time)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_time)
                        .addGap(18, 18, 18)
                        .addComponent(btn_new)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_find)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_open)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_veDau)
                    .addComponent(btn_back)
                    .addComponent(btn_next)
                    .addComponent(btn_veCuoi)
                    .addComponent(lbl_hienThi)
                    .addComponent(btn_exit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hotenActionPerformed

    private void txt_tuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tuoiActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_luongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_luongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_luongActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

//        Employee e1 = new Employee("PH26011", "Nguyen Van Hai", 19, "hainvph26011@fpt.edu.vn", 1200000);
//        Employee e2 = new Employee("PH26023", "Nguyen Chi Thuan", 21, "thuanncph26023@fpt.edu.vn", 9000000);
//        Employee e3 = new Employee("PH26026", "Dao Xuan Lam", 32, "lamdtph26026@fpt.edu.vn", 8500000);
//
//        mangNhanVien.add(e1);
//        mangNhanVien.add(e2);
//        mangNhanVien.add(e3);
//        fillTable();

        // khi an vao thi hien thi
        hienThiLable();
        
    }//GEN-LAST:event_formWindowOpened

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        writeFile();
        
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            addEmployyee();
        } else {
            updateEmployee();
        }
        hienThiLable();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btn_newActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        Employee e = mangNhanVien.get(indexTable());
        writeForm(e);
        index = indexTable(); // gan index
        hienThiLable();
    }//GEN-LAST:event_tblMouseClicked

    private void btn_veDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_veDauActionPerformed
        // TODO add your handling code here:
        index = 0; // lay ra vi tri dau
        writeForm(mangNhanVien.get(index));

        tbl.setRowSelectionInterval(index, index);
        hienThiLable();
    }//GEN-LAST:event_btn_veDauActionPerformed

    private void btn_veCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_veCuoiActionPerformed
        // TODO add your handling code here:
        index = mangNhanVien.size() - 1; // lay ra vi tri cuoi 
        writeForm(mangNhanVien.get(index));

        tbl.setRowSelectionInterval(index, index);
        hienThiLable();
    }//GEN-LAST:event_btn_veCuoiActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        if (index > 0) { // buoc phai nho nhat la 1 vi khi minh an vao thi index no gia di 1
            index--;
            writeForm(mangNhanVien.get(index));
        }

        tbl.setRowSelectionInterval(index, index);
        hienThiLable();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        if (index < mangNhanVien.size() - 1) { // buoc phai luon nhat la size - 2 vi khi an vao thi no len size - 1
            index++;
            writeForm(mangNhanVien.get(index));
        }
        
        tbl.setRowSelectionInterval(index, index);
        hienThiLable();
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        deleteTheoMa();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        // TODO add your handling code here:
        findTheoMa();
    }//GEN-LAST:event_btn_findActionPerformed

    private void txt_maKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_maKeyReleased
        // TODO add your handling code here:
        txt_hoten.setText("");
        txt_tuoi.setText("");
        txt_email.setText("");
        txt_luong.setText("");
    }//GEN-LAST:event_txt_maKeyReleased

    private void btn_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openActionPerformed
        // TODO add your handling code here:
        readFile();
    }//GEN-LAST:event_btn_openActionPerformed

    private void txt_maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maActionPerformed

    /**
     * @param args the command line arguments
     */
    List<Employee> mangNhanVien = new ArrayList<>();
    int index = -1; // tao index de biet khi nao an save la add hay update

    public static void main(String args[]) {
        /* Set the Nimbus looTODO add your handling code here:
        txt_ma.setTek and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        QuanLySinhVien quanLy = new QuanLySinhVien();
        quanLy.setVisible(true);
        Thread th = new Thread(quanLy);
        th.start();
    }

    @Override
    public void run() {
        while(true) {
            SimpleDateFormat fm = new SimpleDateFormat("hh:mm:ss a");
            Date date = new Date();
            String thoiGian = fm.format(date);
            lbl_time.setText(thoiGian);
            
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
            }
        }
    }
    

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel(); // lay ra model trong bang

        model.setRowCount(0); // reset table ve 0 row

        for (Employee employee : mangNhanVien) {
            model.addRow(new Object[]{
                employee.getMaNv(), employee.getHoTen(), employee.getTuoi(),
                employee.getEmail(), employee.getLuong()
            });
        }
    }

    public Employee readForm() { // doc du lieu tu form
        String maNv = txt_ma.getText();
        String hoTen = txt_hoten.getText();
        int tuoi = Integer.parseInt(txt_tuoi.getText());
        String email = txt_email.getText();
        double luong = Double.parseDouble(txt_luong.getText());
        Employee e = new Employee(maNv, hoTen, tuoi, email, luong);
        return e;
    }

    public void writeForm(Employee e) { // write du lieu vao form
        txt_ma.setText(e.getMaNv());
        txt_hoten.setText(e.getHoTen());
        txt_tuoi.setText(e.getTuoi() + "");
        txt_email.setText(e.getEmail());
        txt_luong.setText(e.getLuong() + "");
    }

    public int indexTable() { // ham lay gia gia tri index cua table khi minh an vao table
        return tbl.getSelectedRow();
    }

    public void hienThiLable() {
        lbl_hienThi.setText("Record: " + (index + 1) + " of " + mangNhanVien.size());
    }

    public void clearForm() {
        txt_ma.setText("");
        txt_hoten.setText("");
        txt_tuoi.setText("");
        txt_email.setText("");
        txt_luong.setText("");

        index = -1; // khi minh an vao new thi index ve -1 thi moi co the add 1 nhan vien
        // con an cac nut khac thi index se bi thay doi
    }

    public void addEmployyee() {
        if (kiemTraTrungMa() == false) {
            txt_ma.setBackground(Color.YELLOW);
            txt_ma.requestFocus();
        } else if(kiemTraHoTen()== false) {
            txt_hoten.setBackground(Color.YELLOW);
            txt_hoten.requestFocus();
        } else if(kiemTraTuoi() == false) {
            txt_tuoi.setBackground(Color.YELLOW);
            txt_tuoi.requestFocus();
        }else if(kiemTraEmail() == false) {
            txt_email.setBackground(Color.YELLOW);
            txt_email.requestFocus();
        } else if(kiemTraLuong() == false) {
            txt_luong.setBackground(Color.YELLOW);
            txt_luong.requestFocus();
        }  else {
            mangNhanVien.add(readForm());
            fillTable();
            JOptionPane.showMessageDialog(this, "Ban da them mot Nhan Vien");
        }
    }
    
    

    public void updateEmployee() {
        mangNhanVien.set(indexTable(), readForm());
        fillTable();
        JOptionPane.showMessageDialog(this, "Ban da update mot Nhan Vien");
    }

    public void deleteTheoMa() {
        int count = -1; // tao bien count

        String chuoi = JOptionPane.showInputDialog("Nhap ma muon xoa");
        
        for (int i = 0; i < mangNhanVien.size(); i++) {
            if (chuoi.equalsIgnoreCase(mangNhanVien.get(i).getMaNv())) {
                count = i; // tim trong danh sach neu co thi count = 1
                break;
            }
        }
        if (count == -1) {
            JOptionPane.showMessageDialog(this, "Khong co nhan vien nay!");
        } else {
            mangNhanVien.remove(count);
            fillTable();
            JOptionPane.showMessageDialog(this, "Xoa Thanh Cong");
        }
    }

    public void findTheoMa() {
        int count = -1;

        String tam = JOptionPane.showInputDialog("Moi nhap ma tim kiem");
        
        for (int i = 0; i < mangNhanVien.size(); i++) {
            if (tam.equalsIgnoreCase(mangNhanVien.get(i).getMaNv())) {
                count = i;
                break;
            }
        }
        if (count == -1) {
            JOptionPane.showMessageDialog(this, "Khong tim thay nhan vien nay!");
        } else {
            JOptionPane.showMessageDialog(this, "Da tim thay nhan vien!");
            writeForm(mangNhanVien.get(count));
        }
    }

    
    //---------------------------------------dinh dang---------------------------------
    public boolean kiemTraTrungMa() {
        Boolean kiemTra;
        
        if(txt_ma.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID null!");
            return false;
        }
        for (Employee employee : mangNhanVien) {
            if (txt_ma.getText().equalsIgnoreCase(employee.getMaNv())) {
                JOptionPane.showMessageDialog(this, "ID sinh vien da ton tai!");
                return false;
            }
        }
        
        txt_ma.setBackground(Color.WHITE);
        return true;
    }
    
    public boolean kiemTraHoTen() {
        String danhDang = "[a-zA-z ]+";
        if(txt_hoten.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ho ten khong null!");
            return false;
        } else if(txt_hoten.getText().matches(danhDang) == false) {
            JOptionPane.showMessageDialog(this, "Ho ten khong dung dinh dang!");
            return false;
        }
        
        txt_hoten.setBackground(Color.WHITE);
        return true;
    }

    public boolean kiemTraTuoi() {
        int tuoi;
        
        if(txt_tuoi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tuoi null!");
            return false;
        } 
        try {
            tuoi = Integer.parseInt(txt_tuoi.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Khong dung danh dang tuoi!");
            return false;
        }
        if (tuoi < 16 || tuoi > 55) {
            JOptionPane.showMessageDialog(this, "Nhap tuoi tu 16 den 55!");
            return false;
        }
        
        txt_tuoi.setBackground(Color.WHITE);
        return true;
    }
    
    public boolean kiemTraEmail() {
        String dinhDang = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        
        if(txt_email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email null!");
            return false;
        } else if(txt_email.getText().matches(dinhDang) == false) {
            JOptionPane.showMessageDialog(this, "Khong dung dinh dang email!");
            return false;
        }
        
        txt_email.setBackground(Color.WHITE);
        return true;
    }
    
    public boolean kiemTraLuong() {
        Double luong; 
        
        if(txt_luong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Luong null!");
            return false;
        }
        try {
            luong = Double.parseDouble(txt_luong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Khong dung dinh dang luong!");
            return false;
        }
        if(luong < 5000000) {
            JOptionPane.showMessageDialog(this, "Luong lon it nhat la 5000000!");
            return false;
        }
        
        txt_luong.setBackground(Color.WHITE);
        return true;
    }
    
    
    
    //---------------------------------------------------------------------------

    
    public void writeFile() { // output
        try {
            JFileChooser jc = new JFileChooser();
            int chon = jc.showSaveDialog(null);
            if(chon == 0) {
                String path = jc.getSelectedFile().getPath();
                FileOutputStream fo = new FileOutputStream(path);
                ObjectOutputStream ofo = new ObjectOutputStream(fo);
                ofo.writeObject(mangNhanVien);
                ofo.close();
            }
            
            System.exit(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi ghi file!");
        }
    }
    
    
    public void readFile() { // input
        try {
            JFileChooser jc = new JFileChooser();
            int chon = jc.showSaveDialog(null);
            if(chon == 0) {
                String path = jc.getSelectedFile().getPath();
                FileInputStream fi = new FileInputStream(path);
                ObjectInputStream ifi = new ObjectInputStream(fi);
                mangNhanVien = (List<Employee>) ifi.readObject();
                ifi.close();
                
                fillTable();
                JOptionPane.showMessageDialog(this, "Doc file thanh cong!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi doc file!");
        }
    }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_open;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_veCuoi;
    private javax.swing.JButton btn_veDau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_hienThi;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_luong;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_tuoi;
    // End of variables declaration//GEN-END:variables
}
